Updated to version 2.4.2.
Still experiencing a runtime exception:

java.lang.IllegalArgumentException: requirement failed: The inlets []
and outlets [] must correspond to the inlets [filter.in] and outlets
[out]